### PR TITLE
fix: use single quotes in keystore path to handle paths containing spaces

### PR DESCRIPTION
**Pull request by Jordi-Pineiro**
In the version v1.0.10 the single quotes in the keystore path parameter were removed introducing the bug. 

When the keystore path contains spaces the path is split and taken as multiple parameters, at least in Linux.

### CODE REVIEW

**Comment by Martin-Gonzalez90** [comment]
Thanks @Jordi-Pineiro for the PR.
I will take a look in a moment and merge it 💪

**Comment by MartinGonzalez** [comment]
Thanks @Jordi-Pineiro for the PR. I will take a look at it in a moment 💪

**Review by MartinGonzalez — APPROVED** [review]
Thanks for the contribution 🚀

**Pull request merged**
